/*
 * generated by Xtext 2.28.0
 */
package sing.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import sing.ABLRuntimeModule;
import sing.ABLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ABLIdeSetup extends ABLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ABLRuntimeModule(), new ABLIdeModule()));
	}
	
}
