/**
 * generated by Xtext 2.28.0
 */
package sing.aBL;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.xtext.xbase.XExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abl Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sing.aBL.AblDeclaration#getAblVariable <em>Abl Variable</em>}</li>
 * </ul>
 *
 * @see sing.aBL.ABLPackage#getAblDeclaration()
 * @model
 * @generated
 */
public interface AblDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Abl Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abl Variable</em>' containment reference.
   * @see #setAblVariable(XExpression)
   * @see sing.aBL.ABLPackage#getAblDeclaration_AblVariable()
   * @model containment="true"
   * @generated
   */
  XExpression getAblVariable();

  /**
   * Sets the value of the '{@link sing.aBL.AblDeclaration#getAblVariable <em>Abl Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Abl Variable</em>' containment reference.
   * @see #getAblVariable()
   * @generated
   */
  void setAblVariable(XExpression value);

} // AblDeclaration
