/**
 * generated by Xtext 2.28.0
 */
package sing.aBL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Decision Cycle SM Call Delcaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sing.aBL.DecisionCycleSMCallDelcaration#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see sing.aBL.ABLPackage#getDecisionCycleSMCallDelcaration()
 * @model
 * @generated
 */
public interface DecisionCycleSMCallDelcaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see sing.aBL.ABLPackage#getDecisionCycleSMCallDelcaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link sing.aBL.DecisionCycleSMCallDelcaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // DecisionCycleSMCallDelcaration
