/**
 * generated by Xtext 2.28.0
 */
package sing.aBL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sing.aBL.Model#getName <em>Name</em>}</li>
 *   <li>{@link sing.aBL.Model#getImports <em>Imports</em>}</li>
 *   <li>{@link sing.aBL.Model#getConstants <em>Constants</em>}</li>
 *   <li>{@link sing.aBL.Model#getBehavingEntityName <em>Behaving Entity Name</em>}</li>
 *   <li>{@link sing.aBL.Model#getTeamNeededForSuccessDefault <em>Team Needed For Success Default</em>}</li>
 *   <li>{@link sing.aBL.Model#getDecisionCycleSMCall <em>Decision Cycle SM Call</em>}</li>
 *   <li>{@link sing.aBL.Model#getConflicits <em>Conflicits</em>}</li>
 *   <li>{@link sing.aBL.Model#getAblDeclarations <em>Abl Declarations</em>}</li>
 * </ul>
 *
 * @see sing.aBL.ABLPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see sing.aBL.ABLPackage#getModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link sing.aBL.Model#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Imports</b></em>' containment reference list.
   * The list contents are of type {@link sing.aBL.ImportDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' containment reference list.
   * @see sing.aBL.ABLPackage#getModel_Imports()
   * @model containment="true"
   * @generated
   */
  EList<ImportDeclaration> getImports();

  /**
   * Returns the value of the '<em><b>Constants</b></em>' containment reference list.
   * The list contents are of type {@link sing.aBL.ConstantDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constants</em>' containment reference list.
   * @see sing.aBL.ABLPackage#getModel_Constants()
   * @model containment="true"
   * @generated
   */
  EList<ConstantDeclaration> getConstants();

  /**
   * Returns the value of the '<em><b>Behaving Entity Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Behaving Entity Name</em>' attribute.
   * @see #setBehavingEntityName(String)
   * @see sing.aBL.ABLPackage#getModel_BehavingEntityName()
   * @model
   * @generated
   */
  String getBehavingEntityName();

  /**
   * Sets the value of the '{@link sing.aBL.Model#getBehavingEntityName <em>Behaving Entity Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Behaving Entity Name</em>' attribute.
   * @see #getBehavingEntityName()
   * @generated
   */
  void setBehavingEntityName(String value);

  /**
   * Returns the value of the '<em><b>Team Needed For Success Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Team Needed For Success Default</em>' attribute.
   * @see #setTeamNeededForSuccessDefault(String)
   * @see sing.aBL.ABLPackage#getModel_TeamNeededForSuccessDefault()
   * @model
   * @generated
   */
  String getTeamNeededForSuccessDefault();

  /**
   * Sets the value of the '{@link sing.aBL.Model#getTeamNeededForSuccessDefault <em>Team Needed For Success Default</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Team Needed For Success Default</em>' attribute.
   * @see #getTeamNeededForSuccessDefault()
   * @generated
   */
  void setTeamNeededForSuccessDefault(String value);

  /**
   * Returns the value of the '<em><b>Decision Cycle SM Call</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decision Cycle SM Call</em>' containment reference.
   * @see #setDecisionCycleSMCall(DecisionCycleSMCallDelcaration)
   * @see sing.aBL.ABLPackage#getModel_DecisionCycleSMCall()
   * @model containment="true"
   * @generated
   */
  DecisionCycleSMCallDelcaration getDecisionCycleSMCall();

  /**
   * Sets the value of the '{@link sing.aBL.Model#getDecisionCycleSMCall <em>Decision Cycle SM Call</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decision Cycle SM Call</em>' containment reference.
   * @see #getDecisionCycleSMCall()
   * @generated
   */
  void setDecisionCycleSMCall(DecisionCycleSMCallDelcaration value);

  /**
   * Returns the value of the '<em><b>Conflicits</b></em>' containment reference list.
   * The list contents are of type {@link sing.aBL.ConflictDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conflicits</em>' containment reference list.
   * @see sing.aBL.ABLPackage#getModel_Conflicits()
   * @model containment="true"
   * @generated
   */
  EList<ConflictDeclaration> getConflicits();

  /**
   * Returns the value of the '<em><b>Abl Declarations</b></em>' containment reference list.
   * The list contents are of type {@link sing.aBL.AblDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abl Declarations</em>' containment reference list.
   * @see sing.aBL.ABLPackage#getModel_AblDeclarations()
   * @model containment="true"
   * @generated
   */
  EList<AblDeclaration> getAblDeclarations();

} // Model
