/**
 * generated by Xtext 2.28.0
 */
package sing.aBL;

import org.eclipse.xtext.xbase.XExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sing.aBL.PropertyDeclaration#getType <em>Type</em>}</li>
 *   <li>{@link sing.aBL.PropertyDeclaration#getAblName <em>Abl Name</em>}</li>
 * </ul>
 *
 * @see sing.aBL.ABLPackage#getPropertyDeclaration()
 * @model
 * @generated
 */
public interface PropertyDeclaration extends AblDeclaration
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(XExpression)
   * @see sing.aBL.ABLPackage#getPropertyDeclaration_Type()
   * @model containment="true"
   * @generated
   */
  XExpression getType();

  /**
   * Sets the value of the '{@link sing.aBL.PropertyDeclaration#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(XExpression value);

  /**
   * Returns the value of the '<em><b>Abl Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abl Name</em>' attribute.
   * @see #setAblName(String)
   * @see sing.aBL.ABLPackage#getPropertyDeclaration_AblName()
   * @model
   * @generated
   */
  String getAblName();

  /**
   * Sets the value of the '{@link sing.aBL.PropertyDeclaration#getAblName <em>Abl Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Abl Name</em>' attribute.
   * @see #getAblName()
   * @generated
   */
  void setAblName(String value);

} // PropertyDeclaration
