/*
 * generated by Xtext 2.28.0
 */
package sing.ui.editor;

import org.eclipse.xtext.xbase.ui.editor.XbaseEditor;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class ABLEditor extends XbaseEditor {
}
