/*
 * generated by Xtext 2.28.0
 */
package sing.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ABLUiModule extends AbstractABLUiModule {

	public ABLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
