/**
 * generated by Xtext 2.28.0
 */
package sing.aBL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import sing.aBL.ABLPackage;
import sing.aBL.ActionRegistration;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Action Registration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link sing.aBL.impl.ActionRegistrationImpl#getAblName <em>Abl Name</em>}</li>
 *   <li>{@link sing.aBL.impl.ActionRegistrationImpl#getAblName2 <em>Abl Name2</em>}</li>
 *   <li>{@link sing.aBL.impl.ActionRegistrationImpl#getTypes <em>Types</em>}</li>
 *   <li>{@link sing.aBL.impl.ActionRegistrationImpl#getActName <em>Act Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ActionRegistrationImpl extends AblDeclarationImpl implements ActionRegistration
{
  /**
   * The default value of the '{@link #getAblName() <em>Abl Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAblName()
   * @generated
   * @ordered
   */
  protected static final String ABL_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAblName() <em>Abl Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAblName()
   * @generated
   * @ordered
   */
  protected String ablName = ABL_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getAblName2() <em>Abl Name2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAblName2()
   * @generated
   * @ordered
   */
  protected static final String ABL_NAME2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAblName2() <em>Abl Name2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAblName2()
   * @generated
   * @ordered
   */
  protected String ablName2 = ABL_NAME2_EDEFAULT;

  /**
   * The cached value of the '{@link #getTypes() <em>Types</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypes()
   * @generated
   * @ordered
   */
  protected EList<String> types;

  /**
   * The default value of the '{@link #getActName() <em>Act Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActName()
   * @generated
   * @ordered
   */
  protected static final String ACT_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getActName() <em>Act Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActName()
   * @generated
   * @ordered
   */
  protected String actName = ACT_NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ActionRegistrationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ABLPackage.Literals.ACTION_REGISTRATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAblName()
  {
    return ablName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAblName(String newAblName)
  {
    String oldAblName = ablName;
    ablName = newAblName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ABLPackage.ACTION_REGISTRATION__ABL_NAME, oldAblName, ablName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAblName2()
  {
    return ablName2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAblName2(String newAblName2)
  {
    String oldAblName2 = ablName2;
    ablName2 = newAblName2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ABLPackage.ACTION_REGISTRATION__ABL_NAME2, oldAblName2, ablName2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getTypes()
  {
    if (types == null)
    {
      types = new EDataTypeEList<String>(String.class, this, ABLPackage.ACTION_REGISTRATION__TYPES);
    }
    return types;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getActName()
  {
    return actName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setActName(String newActName)
  {
    String oldActName = actName;
    actName = newActName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ABLPackage.ACTION_REGISTRATION__ACT_NAME, oldActName, actName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ABLPackage.ACTION_REGISTRATION__ABL_NAME:
        return getAblName();
      case ABLPackage.ACTION_REGISTRATION__ABL_NAME2:
        return getAblName2();
      case ABLPackage.ACTION_REGISTRATION__TYPES:
        return getTypes();
      case ABLPackage.ACTION_REGISTRATION__ACT_NAME:
        return getActName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ABLPackage.ACTION_REGISTRATION__ABL_NAME:
        setAblName((String)newValue);
        return;
      case ABLPackage.ACTION_REGISTRATION__ABL_NAME2:
        setAblName2((String)newValue);
        return;
      case ABLPackage.ACTION_REGISTRATION__TYPES:
        getTypes().clear();
        getTypes().addAll((Collection<? extends String>)newValue);
        return;
      case ABLPackage.ACTION_REGISTRATION__ACT_NAME:
        setActName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ABLPackage.ACTION_REGISTRATION__ABL_NAME:
        setAblName(ABL_NAME_EDEFAULT);
        return;
      case ABLPackage.ACTION_REGISTRATION__ABL_NAME2:
        setAblName2(ABL_NAME2_EDEFAULT);
        return;
      case ABLPackage.ACTION_REGISTRATION__TYPES:
        getTypes().clear();
        return;
      case ABLPackage.ACTION_REGISTRATION__ACT_NAME:
        setActName(ACT_NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ABLPackage.ACTION_REGISTRATION__ABL_NAME:
        return ABL_NAME_EDEFAULT == null ? ablName != null : !ABL_NAME_EDEFAULT.equals(ablName);
      case ABLPackage.ACTION_REGISTRATION__ABL_NAME2:
        return ABL_NAME2_EDEFAULT == null ? ablName2 != null : !ABL_NAME2_EDEFAULT.equals(ablName2);
      case ABLPackage.ACTION_REGISTRATION__TYPES:
        return types != null && !types.isEmpty();
      case ABLPackage.ACTION_REGISTRATION__ACT_NAME:
        return ACT_NAME_EDEFAULT == null ? actName != null : !ACT_NAME_EDEFAULT.equals(actName);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (ablName: ");
    result.append(ablName);
    result.append(", ablName2: ");
    result.append(ablName2);
    result.append(", types: ");
    result.append(types);
    result.append(", actName: ");
    result.append(actName);
    result.append(')');
    return result.toString();
  }

} //ActionRegistrationImpl
