/**
 * generated by Xtext 2.28.0
 */
package sing.aBL.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import sing.aBL.ABLPackage;
import sing.aBL.WMERegistration;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>WME Registration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link sing.aBL.impl.WMERegistrationImpl#getWmeClass <em>Wme Class</em>}</li>
 *   <li>{@link sing.aBL.impl.WMERegistrationImpl#getName <em>Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WMERegistrationImpl extends AblDeclarationImpl implements WMERegistration
{
  /**
   * The default value of the '{@link #getWmeClass() <em>Wme Class</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWmeClass()
   * @generated
   * @ordered
   */
  protected static final String WME_CLASS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getWmeClass() <em>Wme Class</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWmeClass()
   * @generated
   * @ordered
   */
  protected String wmeClass = WME_CLASS_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WMERegistrationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ABLPackage.Literals.WME_REGISTRATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getWmeClass()
  {
    return wmeClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWmeClass(String newWmeClass)
  {
    String oldWmeClass = wmeClass;
    wmeClass = newWmeClass;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ABLPackage.WME_REGISTRATION__WME_CLASS, oldWmeClass, wmeClass));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ABLPackage.WME_REGISTRATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ABLPackage.WME_REGISTRATION__WME_CLASS:
        return getWmeClass();
      case ABLPackage.WME_REGISTRATION__NAME:
        return getName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ABLPackage.WME_REGISTRATION__WME_CLASS:
        setWmeClass((String)newValue);
        return;
      case ABLPackage.WME_REGISTRATION__NAME:
        setName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ABLPackage.WME_REGISTRATION__WME_CLASS:
        setWmeClass(WME_CLASS_EDEFAULT);
        return;
      case ABLPackage.WME_REGISTRATION__NAME:
        setName(NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ABLPackage.WME_REGISTRATION__WME_CLASS:
        return WME_CLASS_EDEFAULT == null ? wmeClass != null : !WME_CLASS_EDEFAULT.equals(wmeClass);
      case ABLPackage.WME_REGISTRATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (wmeClass: ");
    result.append(wmeClass);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //WMERegistrationImpl
