/*
 * generated by Xtext 2.28.0
 */
package sing.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import sing.parser.antlr.internal.InternalABLParser;
import sing.services.ABLGrammarAccess;

public class ABLParser extends AbstractAntlrParser {

	@Inject
	private ABLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalABLParser createParser(XtextTokenStream stream) {
		return new InternalABLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ABLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ABLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
