/*
 * generated by Xtext 2.28.0
 */
package sing.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import sing.abl.ui.internal.AblActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ABLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(AblActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		AblActivator activator = AblActivator.getInstance();
		return activator != null ? activator.getInjector(AblActivator.SING_ABL) : null;
	}

}
