/*
 * generated by Xtext 2.28.0
 */
package sing.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractABLScopeProvider extends XbaseBatchScopeProvider {
}
