/*
 * generated by Xtext 2.28.0
 */
package sing.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import sing.abl.ui.internal.AblActivator;

public class ABLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AblActivator.getInstance().getInjector("sing.ABL");
	}

}
